# Generated by Django 5.0.6 on 2024-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exportproduct',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='returnproduct',
            name='created_at',
            field=models.DateField(),
        ),
    ]
