# Generated by Django 5.0.6 on 2024-05-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_returnproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returnproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
